// <auto-generated />
using System;
using API_Manga.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_Manga.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220412093233_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("API_Manga.Models.ForumPost", b =>
                {
                    b.Property<int>("id_Post")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Topicid_Topic")
                        .HasColumnType("INTEGER");

                    b.HasKey("id_Post");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Topicid_Topic");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("API_Manga.Models.ForumReply", b =>
                {
                    b.Property<int>("id_Reply")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForumPostid_Post")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplyDate")
                        .HasColumnType("TEXT");

                    b.HasKey("id_Reply");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ForumPostid_Post");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("API_Manga.Models.ForumTopic", b =>
                {
                    b.Property<int>("id_Topic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mangaid_Manga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_Topic");

                    b.HasIndex("Mangaid_Manga");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("API_Manga.Models.ForumUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDiNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API_Manga.Models.Manga", b =>
                {
                    b.Property<int>("id_Manga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnnoPubblicazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id_Manga");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("API_Manga.Models.ForumPost", b =>
                {
                    b.HasOne("API_Manga.Models.ForumUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("API_Manga.Models.ForumTopic", "Topic")
                        .WithMany()
                        .HasForeignKey("Topicid_Topic");

                    b.Navigation("Creator");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("API_Manga.Models.ForumReply", b =>
                {
                    b.HasOne("API_Manga.Models.ForumUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId");

                    b.HasOne("API_Manga.Models.ForumPost", null)
                        .WithMany("Replies")
                        .HasForeignKey("ForumPostid_Post");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("API_Manga.Models.ForumTopic", b =>
                {
                    b.HasOne("API_Manga.Models.Manga", "Manga")
                        .WithMany()
                        .HasForeignKey("Mangaid_Manga");

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("API_Manga.Models.ForumPost", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
